### ISSUE TITLE
modlog broken/too wide

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#203]
STR:
- BL a file with a long name
- Trigger BL so a new log entry is generated

Result:
Mod log table becomes to wide, overflows "off screen" (truncated); the `breakword` class does not actually work

Suggested fix:
---
Using `table-layout: fixed` would do it, but then you need to also either manually set width on the first table row cells (`th` in this case) or do so in CSS

dolosfile works around this now by:
```css

.page_admin_modlog table {
    table-layout: fixed;
    width: 100%;
}
.page_admin_modlog table th:nth-child(1) {
    width: 15%;
}
.page_admin_modlog table th:nth-child(3) {
    width: 62%;
}
.page_admin_modlog table th:nth-child(4) {
    width: 7ex;
}
```
