### ISSUE TITLE
Update CSS to diffirientiate mods from system messages, trusted users, donators and whitefags

### ISSUE THREAD

**Issue by szero** [Volafile/volafile-bugs#227]
```css
:root {
    /*color propostion, you probably want mods to stay purple tho*/
    --whitenames: #A9BDD0; /*light grey*/
    --namefags: #00FF00; /*green*/
    --donators: #90EE90; /*light green*/
    --trusted-users: #FFFF00; /*yellow*/
    --mods: #FF6C00; /*orange*/
    --system: #D808D8; /*purple*/
}

.chat_message.user .username {
    color: var(--namefags) !important;
}
.chat_message.donator .username {
    color: var(--donators) !important;
}
.chat_message.staff .username {
    color: var(--trusted-users) !important;
}
.chat_message.staff:not(.user) .username,
.chat_message.admin:not(.staff):not(.user) .username {
    color: var(--system) !important;
}
.chat_message.admin .username {
    color: var(--mods) !important;
}
```
